monsters on map + nihl spawn arrow + getting player data fix
misterokaygo/MapAssist pull request #131
Opened 2021-11-05 20:06 UTC by RushTheOne

neat

2021-11-05 21:32 UTC, Nairdaa approved these changes

2021-11-05 21:32 UTC, Nairdaa reviewed
alignment in App.config

2021-11-06 05:22 UTC, misterokaygo requested changes

2021-11-06 05:22 UTC, misterokaygo commented on Helpers/PointOfInterestHandler.cs
> +                        if (obj == GameObject.NihlathakWildernessStartPosition)
This can be moved to QuestObjects list checked above and it should just work.

2021-11-06 05:22 UTC, misterokaygo commented on Helpers/GameMemory.cs
>  using System.Linq;
Refer to my branch https://github.com/misterokaygo/MapAssist/tree/feature/wip-classes-units-on-map-icons for how GameMemory will be structured.

2021-11-06 05:22 UTC, misterokaygo commented on Helpers/GameMemory.cs
> +        public static List<Monster> Monsters = new List<Monster>();
This shouldn't be static it should be apart of GameData.

2021-11-06 05:22 UTC, misterokaygo commented on Helpers/GameMemory.cs
> +                /*IntPtr aPlayerUnit = Read<IntPtr>(processHandle, PlayerUnitPtr);
Remove dead code comments.

2021-11-06 05:22 UTC, misterokaygo commented on Helpers/GameMemory.cs
> +            var unitHashTable = Read<UnitHashTable>(processHandle, startAddress);
If the UnitHashTable works then we should probably use that if it's less recursive than iterating all the rooms.

2021-11-06 05:22 UTC, misterokaygo commented on Helpers/GameMemory.cs
> +                var mapShownByte = Read<UiSettings>(processHandle, IntPtr.Add(processAddress, Offsets.UiSettings)).MapShown;
If leaving this as a byte is somehow more compliant, we can wrap UiSettings in a type etc and access this directly as a boolean property.

2021-11-06 05:22 UTC, misterokaygo commented on Settings/PointOfInterestRendering.cs
> +    public class MobRendering
These should just be PoiRendering settings.

2021-11-06 05:22 UTC, misterokaygo commented on Structs/Monster.cs
> +﻿/**
I think this file is un-necessary. Please refer to my UnitAny class.

2021-11-06 05:22 UTC, misterokaygo commented on Types/NPC.cs
> +    public class NPCs
I like this, but I think it should be static and named `NPC`

2021-11-06 05:22 UTC, misterokaygo commented on App.config
> +		<add key="MobColor.Normal" value="CornflowerBlue"/>
Look out for spacing etc.

2021-11-06 05:22 UTC, misterokaygo commented
Can you start on this branch https://github.com/misterokaygo/MapAssist/tree/feature/wip-classes-units-on-map-icons and re-implement your ideas?

2021-11-07 18:45 UTC, closed without merging